In [3]:
import pandas as pd
import os
import pwd

In [10]:
os.getcwd()

'/Users/mbeliera/Documents/projects/fast-api/fastapi-telus-training2'

In [22]:
user_data = pd.read_csv(os.getcwd() + '/user_data.csv').head()
user_data.head()

,id_user,first_name,last_name,email,created_at
0,c1a8f9d2-7e34-4b6a-a5d1-91f8f6b72a11,Kevin,Turner,kevin.turner@example.com,2026-05-15T08:10:22
1,8f42d6ab-1c57-48a0-93de-2bfc8c91d4e7,Emily,Carter,emily.carter@example.com,2026-05-15T08:14:37
2,3b7e9124-5f0d-4d88-bd3e-7f61f7c8e219,Jason,Mitchell,jason.mitchell@example.com,2026-05-15T08:19:05
3,f5c3a1d8-9b64-41ef-8f3b-12c9d4e5a6f7,Sarah,Collins,sarah.collins@example.com,2026-05-15T08:23:41
4,2d6f8b90-3a74-45ce-91f4-8a7d5c3e2b10,Daniel,Reed,daniel.reed@example.com,2026-05-15T08:27:58

In [38]:
user_data.shape

(5, 5)

In [23]:
reservation_data = pd.read_csv(os.getcwd() + '/reservation_data.csv').head()
reservation_data.head()

,id_reservation,user_id,reservation_date,reservation_time,created_at
0,f3a1d8c4-7b92-4e5a-91d7-3c8f2a6b1e44,c1a8f9d2-7e34-4b6a-a5d1-91f8f6b72a11,2026-05-20,18:30:00,2026-05-15T09:12:45
1,b7d4e2f1-5c88-49ab-8f3d-6a1c9e7b2d55,8f42d6ab-1c57-48a0-93de-2bfc8c91d4e7,2026-05-21,12:00:00,2026-05-15T09:15:10
2,9c5a7e1d-3f64-42b8-b1e9-4d7c2a8f6b33,3b7e9124-5f0d-4d88-bd3e-7f61f7c8e219,2026-05-22,09:15:00,2026-05-15T09:18:22
3,2e8b4d7f-1a35-46c9-92f1-8d6b3c7a5e66,f5c3a1d8-9b64-41ef-8f3b-12c9d4e5a6f7,2026-05-23,20:45:00,2026-05-15T09:21:37
4,7d1c9a4e-6f52-4b8d-a3c7-5e2f1b9d4a77,2d6f8b90-3a74-45ce-91f4-8a7d5c3e2b10,2026-05-24,14:00:00,2026-05-15T09:25:04

In [40]:
full_data = user_data.merge(reservation_data, left_on= "id_user", right_on="user_id", how = "left").drop(columns=['user_id'])

full_data.shape

(5, 9)

In [42]:
full_data.head()

,id_user,first_name,last_name,email,created_at_x,id_reservation,reservation_date,reservation_time,created_at_y
0,c1a8f9d2-7e34-4b6a-a5d1-91f8f6b72a11,Kevin,Turner,kevin.turner@example.com,2026-05-15T08:10:22,f3a1d8c4-7b92-4e5a-91d7-3c8f2a6b1e44,2026-05-20,18:30:00,2026-05-15T09:12:45
1,8f42d6ab-1c57-48a0-93de-2bfc8c91d4e7,Emily,Carter,emily.carter@example.com,2026-05-15T08:14:37,b7d4e2f1-5c88-49ab-8f3d-6a1c9e7b2d55,2026-05-21,12:00:00,2026-05-15T09:15:10
2,3b7e9124-5f0d-4d88-bd3e-7f61f7c8e219,Jason,Mitchell,jason.mitchell@example.com,2026-05-15T08:19:05,9c5a7e1d-3f64-42b8-b1e9-4d7c2a8f6b33,2026-05-22,09:15:00,2026-05-15T09:18:22
3,f5c3a1d8-9b64-41ef-8f3b-12c9d4e5a6f7,Sarah,Collins,sarah.collins@example.com,2026-05-15T08:23:41,2e8b4d7f-1a35-46c9-92f1-8d6b3c7a5e66,2026-05-23,20:45:00,2026-05-15T09:21:37
4,2d6f8b90-3a74-45ce-91f4-8a7d5c3e2b10,Daniel,Reed,daniel.reed@example.com,2026-05-15T08:27:58,7d1c9a4e-6f52-4b8d-a3c7-5e2f1b9d4a77,2026-05-24,14:00:00,2026-05-15T09:25:04